// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type FriendList struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FriendID  uuid.UUID
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Group struct {
	ID          uuid.UUID
	GroupName   string
	OwnerID     uuid.UUID
	Description string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GroupMember struct {
	ID       uuid.UUID
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     sql.NullString
	JoinedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	UserName  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
