version: '0.1'
services:
  app:
    container_name: app_container 
    build: .
    ports:
      - "8000:8000"
    networks:
      - chat_network
    depends_on:
      - mongo_db
  
  mongo_db:
    image: mongo
    container_name: db_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - "40000:27017"
    volumes:
      - mydata:/data/db

    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  mydata: 
    driver: local

  
  