database:
  url: mongodb://localhost:27017
  dbname: chat
  pgurl: postgres://postgres:password@localhost:5430/go_chat?sslmode=disable

server:
  host: localhost
  port: 8000

migration:

  path: internal/constant/query/schemas